- job:
    name: docker-image-cleanup
    project-type: freestyle
    description: |
      Cleanup leftovers of image deployment.
    display-name: 'Docker image cleanup'
    concurrent: false
    node: docker
    builders:
      - shell: |
          set -x
          docker rmi "jjb_${deploy}" "ruby_${deploy}" "host_${deploy}"\
                "node_${deploy}" || echo "Some images were not found"
