- job:
    name: logstash-input-bugzilla_docker-build-node
    project-type: freestyle
    description: |
      Node is a base image which jenkins can run its job on.
    display-name: '[LIP-Bugzilla] Docker build node image'
    concurrent: false
    node: lip-bugzilla_docker
    scm:
      - logstash-input-bugzilla
    builders:
      - shell:
          !include-raw ../scripts/merge.sh
      - shell: |
          set +x
          pushd "${WORKSPACE}/logstash-input-bugzilla_${BUILD_NUMBER}/docker/node"
          if [ $(git diff --stat "HEAD^" -- . | wc -l) -gt 0 ]; then
            echo "============================"
            echo "Docker - Building Node Image"
            echo "============================"
            docker build -t "lip_bugzilla/node_test" .
          else
            docker tag -f abraverm/jenkins:node node_test
            echo "Nothing changed"
          fi
