- job:
    name: docker-image-cleanup
    project-type: freestyle
    description: |
      Cleanup leftovers of image deployment.
    display-name: 'Docker image cleanup'
    concurrent: false
    node: docker
    builders:
      - shell: |
          set -x
          docker rmi jjb_test ruby_test host_test node_test || echo "Some images were not found"
